# Generated by Django 6.0.5 on 2026-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personajes/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('organizacion', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Atacante', 'Atacante'), ('Defensor', 'Defensor')], max_length=20)),
                ('velocidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], max_length=10)),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
    ]
